name: Security Scan

on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Aqua Security Trivy
        uses: aquasecurity/trivy-action@0.19.0
        with:
          scan-type: fs
          path: '.'
          format: table
